on:
  workflow_dispatch:
    inputs:
      VARIABLE: 
        default: "A variable"
        description: This is the name of the variable
        required: true
        type: string
  schedule:
    - cron: '*/5 * * * *'
jobs:
  print-the-varaible:
    name: Print the variable
    runs-on: ubuntu-latest
    env:
      VARIABLE: ${{ inputs.VARIABLE }}
    steps:
      - name: Print the variable
        shell: pwsh
        run: |
          Write-Host "$env:VARIABLE"
          Write-Host "$($env:VARIABLE)"
