on:
  workflow_dispatch:
    inputs:
      VARIABLE: 
        default: "A variable"
        description: This is the name of the variable
        required: true
        type: string
  schedule:
    - cron: '*/5 * * * *'
jobs:
  print-the-varaible:
    name: Print the variable
    runs-on: ubuntu-latest
    env:
      VARIABLE: "default value"
    steps:
      - name: Set variable if input is not empty
        if: ${{ !isEmpty(inputs.VARIABLE) }}
        run: echo "::set-env name=VARIABLE::${{ inputs.VARIABLE }}"
      - name: Print the variable
        run: Write-Host ${{ env.VARIABLE }}
